### ISSUE TITLE
[KK] Default skirt colliders no longer work properly (v1.3.1)

### ISSUE THREAD

**Issue by Jatts-Art** [Njaecha/DynamicBoneDistributionEditor#5]
I've seen a few other people mentioning this same issue on the KK server, and I'm surprised it hasn't been addressed yet. I really like the convenience of this plugin so I hope it does get fixed eventually.

So just for the sake of it, I decided to create an issue thread about it.

![CharaStudio-2024-08-08-22-20-25-Render](https://github.com/user-attachments/assets/84bd6f71-c38c-49ad-a4b8-384a12a67474)
![CharaStudio-2024-08-08-22-06-07-Render](https://github.com/user-attachments/assets/7d279fd0-4d8b-402f-88ea-0dd0913cc9d5)

**Comment by Njaecha** [comment]
Fixed in V1.3.2
