### ISSUE TITLE
Honey Select 2

### ISSUE THREAD

**Issue by Shirakatori** [Njaecha/DynamicBoneDistributionEditor#7]
Are you planning on making a version for honey select 2?
or does an alternative for that already exists for that game?.
I'm asking for char maker / main game, not studio.

**Comment by Njaecha** [comment]
Sorry I don't have plan for supporting games other than koikatsu since I don't play those. Feel free to port the plugin yourself or ask someone to do so though, I will accept Pull Requests in that regard.
